/**
 * Snapshot the generated dist/manifest.json shape so silent drift in tool counts
 * (a tool added without classification, a domain misnamed, an annotation lost)
 * fails CI loudly rather than slipping into a release.
 *
 * The manifest is regenerated by `prepack` and by the CI build step. If you
 * intentionally add or reclassify a tool, run `npm run generate:manifest` and
 * update the snapshot via `npm test -- -u`.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const MANIFEST = resolve(here, '..', 'dist', 'manifest.json');

interface Manifest {
  name: string;
  version: string;
  tool_count: number;
  counts_by_risk: Record<string, number>;
  counts_by_domain: Record<string, number>;
  by_risk: Record<string, string[]>;
  by_domain: Record<string, string[]>;
  tools: Array<{
    name: string;
    title?: string;
    domain: string;
    risk: string;
    description: string;
  }>;
}

let manifest: Manifest;

beforeAll(() => {
  if (!existsSync(MANIFEST)) {
    throw new Error(
      `dist/manifest.json missing — run "npm run generate:manifest" first ` +
        `(in CI this is part of the test job; locally you can run "npm run build && npm run generate:manifest").`,
    );
  }
  manifest = JSON.parse(readFileSync(MANIFEST, 'utf8')) as Manifest;
});

describe('manifest snapshot', () => {
  it('has stable counts_by_risk (v0.7.0: +3 meta tools — 145 total)', () => {
    expect(manifest.counts_by_risk).toEqual({
      sensitive: 3,
      read: 80, // +3 in v0.7.0: meta_health, meta_auth_status, meta_capabilities
      write: 43,
      money: 9,
      public: 10,
      unknown: 0,
    });
  });

  it('has total tool_count = 145', () => {
    expect(manifest.tool_count).toBe(145);
  });

  it('covers exactly the expected 19 domain prefixes', () => {
    const expected = new Set([
      'auth',
      'autoload',
      'calltracking',
      'cpa',
      'cpa_auction',
      'cpa_target',
      'delivery',
      'hierarchy',
      'items',
      'meta',
      'messenger',
      'msg_discounts',
      'orders',
      'promotion',
      'reviews',
      'stock',
      'tariffs',
      'trxpromo',
      'user',
    ]);
    const actual = new Set(Object.keys(manifest.counts_by_domain));
    expect([...actual].sort()).toEqual([...expected].sort());
  });

  it('every tool has a known risk (no "unknown" in the manifest)', () => {
    expect(manifest.counts_by_risk.unknown).toBe(0);
  });

  it('snapshot: full tool roster (name, risk, domain)', () => {
    const inventory = manifest.tools.map((t) => `${t.risk.padEnd(9)} ${t.domain.padEnd(15)} ${t.name}`);
    expect(inventory).toMatchSnapshot();
  });

  it('v0.7.2: EVERY tool has a non-empty human-readable title', () => {
    const withTitle = manifest.tools.filter((t) => typeof t.title === 'string' && t.title.length > 0);
    // v0.7.2 backfilled titles across all domains — full coverage is now an invariant.
    // A new tool added without a title will fail this test (re-run generate:manifest + add a title).
    expect(withTitle.length).toBe(manifest.tool_count);
    const missing = manifest.tools.filter((t) => !t.title).map((t) => t.name);
    expect(missing).toEqual([]);
  });
});
